# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: greatgc-flow.Engram
PackageVersion: 3.7.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: Engram.exe
    PortableCommandAlias: engram
ReleaseDate: 2026-10-03
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/greatgc-flow/Engram/releases/download/v3.7.0/Engram-v3.7.0-portable-x64.zip
    InstallerSha256: A3CE8447875834351B23ADD57C3430B79255602CBFD70E306B5E67B64248DA7E
ManifestType: installer
ManifestVersion: 1.12.0
