# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: greatgc-flow.Engram
PackageVersion: 3.4.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: Engram.exe
    PortableCommandAlias: engram
ReleaseDate: 2026-09-28
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/greatgc-flow/Engram/releases/download/v3.4.3/Engram-v3.4.3-portable-x64.zip
    InstallerSha256: 283CD22708C0899A3DE4878E26774E152EE6AE4A35BD251DA7272595A672F017
ManifestType: installer
ManifestVersion: 1.12.0
