# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: greatgc-flow.Engram
PackageVersion: 3.4.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: Engram.exe
    PortableCommandAlias: engram
ReleaseDate: 2026-09-28
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/greatgc-flow/Engram/releases/download/v3.4.4/Engram-v3.4.4-portable-x64.zip
    InstallerSha256: D3828A8A09307044D7AE4CBCD3432B16026F0AA7B47EEC9FCEFC89AE882FEAE9
ManifestType: installer
ManifestVersion: 1.12.0
